return {
    Items = {
        {
            Id = "AwarenessBoost",
            DisplayName = "Awareness",
            Stat = "Awareness",
            Icon = "rbxassetid://108300702326871",
            Cost = 3,
            BoostPercent = 5,
            MaxLevel = 1000,
        },
        {
            Id = "CrystalBoost",
            DisplayName = "Crystals",
            Stat = "CrystalValue",
            Icon = "rbxassetid://78458877619165",
            Cost = 3,
            BoostPercent = 5,
            MaxLevel = 1000,
        },
        {
            Id = "AstralEchoBoost",
            DisplayName = "Astral Echoes",
            Stat = "AstralEcho",
            Icon = "rbxassetid://118132965740444",
            Cost = 3,
            BoostPercent = 5,
            MaxLevel = 1000,
        },
        {
            Id = "EssenceBoost",
            DisplayName = "Essences",
            Stat = "Essences",
            Icon = "rbxassetid://128072050393886",
            Cost = 3,
            BoostPercent = 5,
            MaxLevel = 1000,
        },
    },

    DefaultStock = 5,
    RefreshInterval = 3600, -- 1 hour
    BoostMultiplierPerLevel = 0.05, -- 5% per level
}
