-- Add new entries to the TOP of this list (most recent first)
return {
    {
        Version = "v1.0.3",
        Title   = "Crystal Collection Update",
        Date    = "April 15th, 2026",
        Bullets = {
            "Added crystal combos! Keep collecting to get a crystal multiplier!",
            "Added crystal collection visuals",
        },
    },
    {
        Version = "v1.0.2",
        Title   = "Boosts update",
        Date    = "April 15th, 2026",
        Bullets = {
            "Free Meditate Anywhere and Meditation Speed boosts granted daily",
            "New tutorial",
        },
    },
    {
        Version = "v1.0.1",
        Title   = "Leaderboard Fix",
        Date    = "April 14th, 2026",
        Bullets = {
            "Boards now refresh independently",
            "Removed corrupted old scores",
            "Rejoin new server to see updated boards"
        },
    },
    {
        Version = "v1.0.0",
        Title   = "Initial Release",
        Date    = "April 3rd, 2026",
        Bullets = {
            "Initial release"
        },
    },
}
